# default configuration

baseURL = "/"
title   = "Hugo Theme: hugo-pure"

languageCode   = "en-us"
hasCJKLanguage = true

[markup]
_merge    = "deep"
[markup.highlight]
_merge    = "deep"
noClasses = false
[markup.tableOfContents]
_merge    = "deep"
endLevel  = 2

[menus]

[[menus.main]]
identifier = "Articleshome"
name       = "Article Home"
pageRef    = "/"
weight     = 1

[[menus.main]]
identifier = "home"
name       = "Home Page"
url    = "https://eli-watson.github.io/Home/"
weight     = 2



[[menus.main]]
identifier = "About"
name       = "About"
url    = "https://eli-watson.github.io/Home/Pages/About.html"
weight     = 3

[[menus.main]]
identifier = "Games"
name       = "Games"
url    = "https://eli-watson.github.io/Home/Pages/Games.html"
weight     = 4

[[menus.main]]
identifier = "Links"
name       = "Links"
url    = "https://eli-watson.github.io/Home/Pages/Links.html"
weight     = 5


[[menus.main]]
identifier = "Login"
name       = "Login"
url    = "https://eli-watson.github.io/Home/Pages/Login.html"
weight     = 6




#[params]
#doubleColumns = true

#[outputFormats]
#[outputFormats.myjson]
#baseName  = "myfilename"
#mediaType = "application/json"
#[outputs]
#home = ["html", "rss", "myjson"]

