name: Sync Folders

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout RepoB
        uses: actions/checkout@v2
      
      - name: Run sync script
        run: |
          bash sync_folders.sh
